// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALNOgyYW4vECg4PP1uGklwMd745IK0AlM',
    appId: '1:687270611774:web:981fcd84f287046f8fba6f',
    messagingSenderId: '687270611774',
    projectId: 'basileia-f390e',
    authDomain: 'basileia-f390e.firebaseapp.com',
    storageBucket: 'basileia-f390e.firebasestorage.app',
    measurementId: 'G-PFC1WTVGYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo3JYySE61gsrO0A3jaY6pZ2X9UCt-UXc',
    appId: '1:687270611774:android:f09fe820977ea2b68fba6f',
    messagingSenderId: '687270611774',
    projectId: 'basileia-f390e',
    storageBucket: 'basileia-f390e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuPatoCF6x6HIQVgN_UdRhisS-bf1OFs8',
    appId: '1:687270611774:ios:632a2ee6771532368fba6f',
    messagingSenderId: '687270611774',
    projectId: 'basileia-f390e',
    storageBucket: 'basileia-f390e.firebasestorage.app',
    iosBundleId: 'com.example.baseliaeFlutter',
  );
}
